FROM jenkins/jenkins:2.222.1

USER root
RUN install -d -o jenkins -g jenkins -m 0770 /var/log/jenkins

USER jenkins

ENV JAVA_OPTS="-Xmx8192m"
ENV JENKINS_OPTS=" --handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log"
